system.nenu.*.third_party.micro_site:
  type: mapping
  label: 'Micro site settings'
  mapping:
    site_id:
      type: integer
      label: 'Site ID'
micro_site.settings:
  type: config_object
  label: 'Micro site settings'
  mapping:
    base_url:
      type: string
      label: 'The base url site which hosts sites entities'
    base_scheme:
      type: string
      label: 'The master host scheme'
    public_url:
      type: string
      label: 'The url on which the master host will be accessible'
    skip_validation_dns:
      type: boolean
      label: 'Skip validation DNS'
micro_site.site_type.*:
  type: config_entity
  label: 'Site type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    menu:
      type: boolean
      label: 'the site type has a menu'
    vocabulary:
      type: boolean
      label: 'the site type has a vocabulary'
    uuid:
      type: string
    types:
      type: sequence
      label: 'Node types'
      sequence:
        type: string
        label: 'Node type'
    typesTab:
      type: sequence
      label: 'Node types form available as a tab'
      sequence:
        type: string
        label: 'Node type'
    usersManagement:
      type: boolean
      label: 'the site type can manage users'
